name = "PythonToJuliaHelper"
uuid = "537e76d0-1091-11e9-0230-9df6152dd0df"
authors = ["Diego Javier Zea <diegozea@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
